name: Build and Publish

on:
  push:
    branches:
      - "master"
    paths:
      - .github/workflows/**
      - packages/node-red/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_TOKEN }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: packages/node-red

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./packages/node-red
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            kyuda/node-red:latest
            kyuda/node-red:${{ steps.package-version.outputs.current-version}}